const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
    geometry: { type: "Point", coordinates: [-118.689423, 34.035591] },
    categories: ["trending", "amazing pools"],
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
    geometry: { type: "Point", coordinates: [-74.006015, 40.712728] },
    categories: ["iconic cities", "rooms"],
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
    geometry: { type: "Point", coordinates: [-106.82356, 39.191113] },
    categories: ["mountain", "snow"],
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Florence",
    country: "Italy",
    geometry: { type: "Point", coordinates: [11.25564, 43.769796] },
    categories: ["castle", "iconic cities"],
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 800,
    location: "Portland",
    country: "United States",
    geometry: { type: "Point", coordinates: [-122.674194, 45.520247] },
    categories: ["tree", "mountain"],
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door and onto the white sandy beach. This beachfront home features a private pool and stunning ocean views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    geometry: { type: "Point", coordinates: [-86.842576, 21.152747] },
    categories: ["amazing pools", "trending"],
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. Cozy up by the fireplace in the evening.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
    geometry: { type: "Point", coordinates: [-120.050353, 39.088541] },
    categories: ["mountain", "snow"],
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this sleek penthouse with private terrace.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    geometry: { type: "Point", coordinates: [-118.242766, 34.053691] },
    categories: ["iconic cities", "trending"],
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
    geometry: { type: "Point", coordinates: [7.228677, 46.096101] },
    categories: ["snow", "mountain"],
  },
  {
    title: "Safari Tent in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari tent surrounded by nature and wildlife.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
    geometry: { type: "Point", coordinates: [34.698383, -2.371291] },
    categories: ["farms", "trending"],
  },
  {
    title: "Historic Canal House",
    description: "Stay in a remarkably preserved canal house in Amsterdam's historic center with canal views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands",
    geometry: { type: "Point", coordinates: [4.892453, 52.37308] },
    categories: ["iconic cities", "rooms"],
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire private island to yourself with pristine beaches and crystal clear waters.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 10000,
    location: "Fiji",
    country: "Fiji",
    geometry: { type: "Point", coordinates: [178.438578, -18.119678] },
    categories: ["amazing pools", "trending"],
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Escape to the English countryside in this quaint stone cottage with a blooming garden.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Cotswolds",
    country: "United Kingdom",
    geometry: { type: "Point", coordinates: [-0.230334, 51.748943] },
    categories: ["castle", "farms"],
  },
  {
    title: "Historic Brownstone in Boston",
    description: "Step back in time in this elegant Boston brownstone with historic charm and contemporary comforts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Boston",
    country: "United States",
    geometry: { type: "Point", coordinates: [-71.05783, 42.358834] },
    categories: ["iconic cities", "rooms"],
  },
  {
    title: "Beachfront Bungalow in Bali",
    description: "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with traditional Balinese decor.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Bali",
    country: "Indonesia",
    geometry: { type: "Point", coordinates: [115.19192, -8.22713] },
    categories: ["amazing pools", "trending"],
  },
  {
    title: "Mountain View Cabin in Banff",
    description: "Enjoy breathtaking mountain vistas from this cozy log cabin nestled in the Canadian Rockies.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Banff",
    country: "Canada",
    geometry: { type: "Point", coordinates: [-115.572077, 51.175076] },
    categories: ["mountain", "snow"],
  },
  {
    title: "Art Deco Apartment in South Beach",
    description: "Step into the glamour of the 1930s in this stylish Art Deco apartment just steps from the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    location: "Miami",
    country: "United States",
    geometry: { type: "Point", coordinates: [-80.193597, 25.774157] },
    categories: ["iconic cities", "amazing pools"],
  },
  {
    title: "Tropical Villa in Phuket",
    description: "Escape to a tropical paradise in this luxurious villa with a private infinity pool and lush gardens.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Phuket",
    country: "Thailand",
    geometry: { type: "Point", coordinates: [98.352929, 7.936602] },
    categories: ["amazing pools", "trending"],
  },
  {
    title: "Historic Castle in Scotland",
    description: "Live like royalty in this majestic Scottish castle surrounded by grand lochs and ancient ruins.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Scottish Highlands",
    country: "United Kingdom",
    geometry: { type: "Point", coordinates: [-5.0, 56.8] },
    categories: ["castle", "mountain"],
  },
  {
    title: "Desert Oasis in Dubai",
    description: "Experience luxury in the desert with modern architecture, private plunge pool, and dune views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 5000,
    location: "Dubai",
    country: "United Arab Emirates",
    geometry: { type: "Point", coordinates: [55.188562, 25.074282] },
    categories: ["iconic cities", "amazing pools"],
  },
  {
    title: "Rustic Log Cabin in Montana",
    description: "Unwind in nature in this handcrafted log cabin with views of sprawling meadows and starry skies.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1100,
    location: "Montana",
    country: "United States",
    geometry: { type: "Point", coordinates: [-109.638757, 47.375267] },
    categories: ["farms", "mountain"],
  },
  {
    title: "Beachfront Villa in Greece",
    description: "Enjoy panoramic views of the Mediterranean in this whitewashed villa with sun terraces in Mykonos.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Mykonos",
    country: "Greece",
    geometry: { type: "Point", coordinates: [25.392315, 37.451394] },
    categories: ["amazing pools", "iconic cities"],
  },
  {
    title: "Eco-Friendly Treehouse Retreat",
    description: "Stay in an open-air canopy treehouse high up in the lush rainforests of Costa Rica.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 750,
    location: "Costa Rica",
    country: "Costa Rica",
    geometry: { type: "Point", coordinates: [-84.07391, 9.748917] },
    categories: ["tree", "trending"],
  },
  {
    title: "Historic Cottage in Charleston",
    description: "Charming historic cottage with a private courtyard and original architectural details.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    location: "Charleston",
    country: "United States",
    geometry: { type: "Point", coordinates: [-79.939931, 32.788436] },
    categories: ["rooms", "iconic cities"],
  },
  {
    title: "Modern Apartment in Tokyo",
    description: "Experience the electric energy of Tokyo from this sleek, modern apartment right next to Shibuya.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Tokyo",
    country: "Japan",
    geometry: { type: "Point", coordinates: [139.763895, 35.67686] },
    categories: ["iconic cities", "trending"],
  },
  {
    title: "Lakefront Cabin in New Hampshire",
    description: "Spend summers swimming and winters snowshoeing at this quiet lakefront cabin in the woods.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1300,
    location: "New Hampshire",
    country: "United States",
    geometry: { type: "Point", coordinates: [-71.655399, 43.484913] },
    categories: ["mountain", "tree"],
  },
  {
    title: "Luxury Villa in the Maldives",
    description: "Stay in an overwater bungalow with direct ocean access and endless turquoise waters.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 6000,
    location: "Maldives",
    country: "Maldives",
    geometry: { type: "Point", coordinates: [73.5135, 4.1755] },
    categories: ["amazing pools", "trending"],
  },
  {
    title: "Ski Chalet in Aspen",
    description: "Cozy timber lodge with a roaring stone fireplace and hot tub after a long day on the slopes.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Aspen",
    country: "United States",
    geometry: { type: "Point", coordinates: [-106.82356, 39.191113] },
    categories: ["snow", "mountain"],
  },
  {
    title: "Secluded Beach House in Costa Rica",
    description: "Escape to this secluded beach house on the Pacific coast. Surf the waves or relax on the veranda.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Costa Rica",
    country: "Costa Rica",
    geometry: { type: "Point", coordinates: [-84.07391, 9.748917] },
    categories: ["amazing pools", "tree"],
  },
];

module.exports = { data: sampleListings };
